### ISSUE TITLE
Show how to use Karma and Webpack for tests when using the Dojo loader

### ISSUE THREAD

**Issue by dgwaldo** [tomwayson/esri-webpack-babel#5]
Using this method and trying to run tests I get an error from Karma.

ReferenceError: Can't find variable: __WEBPACK_EXTERNAL_MODULE_662__

Adding in the files to my karma.config then gives me a loading error.

     files: [
       '../vendor/4.1/esri/Map.js',
       '../vendor/4.1/esri/views/SceneView.js',
       '../vendor/4.1/esri/views/MapView.js',
       '../vendor/4.1/esri/widgets/Search.js',
       '../vendor/4.1/esri/geometry/Point.js',
       '../vendor/4.1/esri/symbols/SimpleMarkerSymbol.js',
       '../vendor/4.1/esri/Graphic.js',
        { pattern: './karma-test-shim.js', watched: false }
    ],

 ReferenceError: Can't find variable: define

I've also tried loading the esri/init.js file.  Essentially I guess I'm not sure how to bootstrap my tests now that I'm using the Dojo loader in a script tag in my html file.  An example of how to do this for testing would be great.  

I've got a small app that I'm using as an Angular-2 testing app.  I've got a branch I've loaded maps in if that would be of help to look at. [https://github.com/dgwaldo/black-book]
(https://github.com/dgwaldo/black-book)

**Comment by tomwayson** [comment]
I agree that this repo should show how to run unit tests. Thank you for opening this issue.

https://github.com/lobsteropteryx/esri-webpack-typescript includes a working karma/webpack/esri test configuration, but I didn't have time to get it working for babel/JSAPI 3.x when I forked this repo, so I removed it. That repo is using [karma-dojo](https://github.com/karma-runner/karma-dojo) to load the esri modules as I demonstrate in my [esri-karma-tutorial](https://github.com/tomwayson/esri-karma-tutorial) - this is what you need to do instead of trying to include the files directly like in your code snippet above. It's a Dojo thing. Don't ask.

At a high level, the steps to get this fork to run tests the way the upstream repo does are:
1. copy over the related karma/webpack config files and configuring them for babel instead of typescript
2. copy over the as the test-main.js from [spec](https://github.com/lobsteropteryx/esri-webpack-typescript/tree/master/src/test/spec) folder and configure for JSAPI 3
3. add a [test entry to the package.json scripts](https://github.com/lobsteropteryx/esri-webpack-typescript/blob/master/package.json#L8)

A few of things I might do different than that repo would be to:
- place spec files inline w/ the modules they test (like [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) and angular-cli do) and generally look to angular2-webpack-starter for testing conventions/patterns
- would prefer to write a test on an existing module rather than including a dummy module just for the sake of testing

**Comment by dgwaldo** [comment]
Thanks I'll be looking at https://github.com/tomwayson/angular-cli-esri tonight to see if I can get my tests going again.  Not many resources for setting this stuff up, glad I found these repos.

**Comment by tomwayson** [comment]
Great.

FWIW I haven't yet worked on either the [unit](https://github.com/tomwayson/angular-cli-esri/issues/5) nor the [e2e](https://github.com/tomwayson/angular-cli-esri/issues/6) tests there either. They're passing, but I'm not testing any of the map related code yet. Pull requests are welcome! 😉 

As far as unit tests go, the difference w/ the approach used in that repo is that I _think_ you won't need to do all the steps I outlined above to get the unit tests to pass. Instead you would just mock the service(s) that load the esri modules.

**Comment by tomwayson** [comment]
FYI - Those tests are now successfully testing the map using mocks and w/o having to configure Karma to load the ArcGIS API for JavaScript. See: https://github.com/tomwayson/esri-angular-cli-example/issues/5  

Unfortunately, we can't do it that way in this repo, we'll still have to follow the steps I outline above.  Even though the pattern has been established in that repo, and has since been implemented in https://github.com/tomwayson/angular2-esri-example/pull/32, I still think there's value in adding it here and/or in https://github.com/Robert-W/esri-redux for the benefit of the React folks.

**Comment by tomwayson** [comment]
Closing this as I'm deprecating this repo in favor of using [esri-loader](https://github.com/Esri/esri-loader/).
