### ISSUE TITLE
use the same config,and load module by AMD,but not work

### ISSUE THREAD

**Issue by westfalenxqq** [tomwayson/esri-webpack-babel#7]
I use the same config
![image](https://cloud.githubusercontent.com/assets/8254415/21087507/6186d510-c061-11e6-902d-406f3c8d8610.png)
and i load module by amd
![image](https://cloud.githubusercontent.com/assets/8254415/21087513/7c2634c4-c061-11e6-8820-ee4bdb2484b5.png)
but the bundle
![image](https://cloud.githubusercontent.com/assets/8254415/21087527/90b3d2e8-c061-11e6-856c-004973ca1657.png)
expected:
define(["dojo/ready"], function(ready) { module.exports = ready; })

**Comment by tomwayson** [comment]
Can you show the rest of your index.html, in particular your `dojoConfig`? It is not clear how `app` will be resolved.

**Comment by westfalenxqq** [comment]
Thank you for your reply！
I init arcgis api by local url,and require the bundle.
![image](https://cloud.githubusercontent.com/assets/8254415/21123487/fd682cec-c113-11e6-8bc8-bb813fc626bb.png)

**Comment by tomwayson** [comment]
So is this working for you now?

**Comment by westfalenxqq** [comment]
Unfortunately, It not works yet. Webpack dont bundle the external dojo module as expected

**Comment by tomwayson** [comment]
The dojo modules are **not** expected to be in the bundles because they are listed in the [externals section](https://webpack.github.io/docs/library-and-externals.html#applications-and-externals) section of the webpack config. See [how it works](https://github.com/tomwayson/esri-webpack-babel#how-it-works) and [this blog post](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/) for more information.

Are you seeing a specific error message?

What is "app" and where is that `requre()` call executed? A module (i.e. a file named app.js), a package, a path? I am not really able to help you when you only provide screenshots of part of your files. There is not enough information here to diagnose what is happening.

**Comment by westfalenxqq** [comment]
Thank you for your patience!
I upload my code on the github [esri-webpack-test]( https://github.com/westfalenxqq/esri-webpack-test),
I hope it can help you  find out the problem.

**Comment by tomwayson** [comment]
Thank you for uploading the code, but what is the error that I'm looking for?

**Comment by tomwayson** [comment]
OK, now I see what the problem is.

For what you're trying to do, I would suggest using https://github.com/Esri/angular-esri-map - that library works like [esri-loader](https://github.com/tomwayson/esri-loader) for Angular 1.x.

We don't have an example of how to use that in an application built with webpack, but I'm sure it could be added to something like https://github.com/preboot/angular-webpack.

You definitely don't want to use that [bootstrap.js](https://github.com/westfalenxqq/esri-webpack-test/blob/master/scripts/bootstrap.js) script with anything but the dojo loader. I would suggest not using it at all.

**Comment by westfalenxqq** [comment]
Thanks for that blog post,i will try anohter way.
